public loader
public actualpart
public filename
public numodrives,numosystems,numoselected,HDIDs
public firstpoint,transpoint,packet,EBIOS?,beeper?,floppy?
public enableFX?,lastboot?,defchoi,delay
public highcolor,menucolor
public dummy
public targetdisk

public correctdefault,toascii,setpos

extrn B_commandline:byte
extrn H_entername:byte
extrn H_enterpasswd:byte
extrn S_enterscan:byte
extrn H_FAT:byte
extrn H_entermpass:byte
extrn H_enterdelay:byte
extrn H_enterdefault:byte
extrn Win95?:byte
extrn readint:byte
extrn writeint:byte
extrn actualHD:byte
extrn oldpos:word
extrn helpline2:byte
extrn delaypos:word
extrn defaultpos:word
extrn floppypos:word
extrn beeppos:word
extrn hidemenupos:word
extrn masterpos:word
extrn blockmatrix:word

extrn drawscreen1:near
extrn drawscreen2:near
extrn clearwindow:near
extrn putwindow:near
extrn gotoXY:near
extrn showcursor:near
extrn hidecursor:near
extrn Allocate:near
extrn resizemem:near
extrn freemem:near
extrn getMBRs:near
extrn getsectors:near
extrn checknumodrives:near
extrn savemenu:near
extrn highlight:near
extrn moveblock:near
extrn printattr:near
extrn printhelpline:near
extrn commandline:near
extrn checkcmdline:near
